---
title: "Scrape Bible"
author: "Dr. Lema Logamou Seknewna & Sakayo Toadoum Sari"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Required packages
```{r warning=FALSE, message=FALSE}
rm(list = ls())
library(rvest)
library(tidyverse)
library(openxlsx)
library(stringr)
```


```{r}
bible = "BIRD"
all_books <- c("GEN", "EXO", "LEV", "NUM", "DEU", "JOS", "JDG", "RUT", "1SA", 
               "2SA", "1KI", "2KI", "1CH", "2CH", "EZR", "NEH", "EST", "JOB",
               "PSA", "PRO", "ECC", "SNG", "ISA", "JER", "LAM", "EZK", "DAN", 
               "HOS", "JOL", "AMO", "OBA", "JON", "MIC", "NAM", "HAB", "ZEP", 
               "HAG", "ZEC", "MAL", "MAT", "MRK", "LUK", "JHN", "ACT", "ROM", 
               "1CO", "2CO", "GAL", "EPH", "PHP", "COL", "1TH", "2TH", "1TI", 
               "2TI", "TIT", "PHM", "HEB", "JAS", "1PE", "2PE", "1JN", "2JN", 
               "3JN", "JUD", "REV")

bible_num = 387

# function that will detect the next verse if it exists
next_verse <- function(prev_verse){
  v <- strsplit(prev_verse, split = "\\.")[[1]]
  num <- as.numeric(v[2]) + 1
  next_v <- v
  next_v[2] <- num
  next_v <- paste(next_v, collapse = ".")
  return(next_v)
}
```


```{r}
get_verses <- function(bible, bible_num){
  first_verses = first_verses <- as.list(paste0(all_books, ".1.", bible))
  get_all_bible <- lapply(first_verses, function(url){
    verses <- list()
  
    while (TRUE) {
      url_sba <- paste0("https://www.bible.com/bible/", bible_num, "/", url)
      cat(url, "\n")
    
      links <- read_html(url_sba) %>% html_nodes("a") %>% html_attr("href")
      text <- read_html(url_sba) %>% html_nodes("span") %>% html_text()
      text <- str_trim(text)
      text <- text[grepl("^[0-9]{1,3}[A-Za-z()“‘]+", text)]
      
      verses[[url]] <- text
      check_next <- grep(url %>% next_verse(), links)
      
      if (length(check_next) != 0){
        cat("The next chapter", url %>% next_verse(), "exists. Getting data ...\n")
        url <- url %>% next_verse()
        url_sba <- paste0("https://www.bible.com/bible/", version, "/", url)
      } else {
        cat("Moving to the next book.\n")
        break
      }
    }
    verses
  })
  
  return(get_all_bible)
}
```


```{r}
# get_all_bible <- get_verses(bible, bible_num)
```


## Process the french version
```{r}
translation <- "NIV"
bible_tr_num <- 111
get_all_bible <- get_verses(bible, bible_num)
get_all_bible_tr <- get_verses(translation, bible_tr_num)
# mussey <- get_verses("BMS", 1130)


# function to remove cross-references
remove_crossref <- function(x){
  # x <- gsub("“|‘", "", x)
  x[grepl("^[0-9]{1,3}[A-Za-z()“‘]+", x)]
}

# x <- get_all_bible[[1]]$GEN.3.BIRD
# remove_crossref(x)
```


## Merging data
```{r}
merge_all <- function(x_list){
  x_list_processed <- lapply(x_list, function(list_element){
    n <- names(list_element)
    to_dataframe <- lapply(n, function(i){
      chp_id <- paste0(strsplit(i, split = "\\.")[[1]][1:2], collapse = ".")
      verse_id <- as.numeric(gsub("([0-9]+).*$", "\\1", remove_crossref(list_element[[i]])))
      chapter <- data.frame(ChapterID = chp_id, 
                            VerseID = verse_id,
                            Content = remove_crossref(list_element[[i]]))
    })
  }) %>% bind_rows()
  return(x_list_processed)
}

# Number of verses by chapter


all_bible <- merge_all(get_all_bible)
all_bible_tr <- merge_all(get_all_bible_tr)

# Merge all
data <- all_bible %>% full_join(all_bible_tr, by = c("ChapterID", "VerseID")) %>% 
  rename(Content = Content.x, Translation = Content.y)
# View(data)


write.xlsx(data, "scrapped_Bible.xlsx")
```